name: myserver
description: A server app using the shelf package and Docker.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.0

dependencies:
  args: ^2.4.0
  dotenv: ^4.2.0
  encrypt: ^5.0.3
  get_it: ^7.7.0
  googleapis: ^13.2.0
  googleapis_auth: ^1.6.0
  http: ^1.2.2
  jaguar_jwt: ^3.0.0
  jwt_decoder: ^2.0.1
  logger: ^2.4.0
  mongo_dart: ^0.10.3
  pointycastle: ^3.9.1
  shelf: ^1.4.0
  shelf_router: ^1.1.0
  synchronized: ^3.3.0+3
  uuid: ^4.5.1
  watcher: ^1.1.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
